### ISSUE TITLE
Mission Upload Example

### ISSUE THREAD

**Issue by dawit1989** [mavlink/MAVSDK-CSharp#7]

**Comment by dawit1989** [comment]
Please give me some examples.

**Comment by pacewicz** [comment]
I see the `Mission.UploadMission()` method does not take any parameters - but it should. I will adjust the Jinja templates so that requests with parameters are formulated correctly.

**Comment by dawit1989** [comment]
it will be helpful if you add some examples too for both upload and download.
Thanks

**Comment by dawit1989** [comment]
can we use java template https://github.com/mavlink/MAVSDK-Java/tree/master/sdk/templates since mission upload and download works well?

**Comment by pacewicz** [comment]
That was the plan, actually - but I can't really get the parameters to appear everywhere they should, see #9.

**Comment by dawit1989** [comment]
still mission doesn't work

**Comment by pacewicz** [comment]
@dawit1989, mission uploads now work as expected, there was a problem with how we generated code for interfacing with the MAVSDK server. I addressed that in #9.

**Comment by dawit1989** [comment]
thanks
